Initial pass removing Pi-hole from the code and changing it to X-filter in order to comply with Pi-hole licensing requirements.

diff --git a/xfilter b/xfilter
--- a/xfilter
+++ b/xfilter
@@ -1,27 +1,27 @@
 #!/bin/bash
 
-# Pi-hole: A black hole for Internet advertisements
-# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
+# X-filter: A black hole for Internet advertisements
+# (c) 2017 X-filter, LLC (https://x-filter.net)
 # Network-wide ad blocking via your own hardware.
 #
-# Controller for all pihole scripts and functions.
+# Controller for all xfilter scripts and functions.
 #
 # This file is copyright under the latest version of the EUPL.
 # Please see LICENSE file for your rights under this license.
 
-readonly PI_HOLE_SCRIPT_DIR="/opt/pihole"
-readonly gravitylist="/etc/pihole/gravity.list"
-readonly blacklist="/etc/pihole/black.list"
+readonly X_FILTER_SCRIPT_DIR="/opt/xfilter"
+readonly gravitylist="/etc/xfilter/gravity.list"
+readonly blacklist="/etc/xfilter/black.list"
 
 # setupVars is not readonly here because in some funcitons (checkout),
 # it might get set again when the installer is sourced. This causes an
 # error due to modifying a readonly variable.
-setupVars="/etc/pihole/setupVars.conf"
+setupVars="/etc/xfilter/setupVars.conf"
 
-readonly colfile="${PI_HOLE_SCRIPT_DIR}/COL_TABLE"
+readonly colfile="${X_FILTER_SCRIPT_DIR}/COL_TABLE"
 source "${colfile}"
 
-resolver="pihole-FTL"
+resolver="xfilter-FTL"
 
 # Must be root to use this tool
 if [[ ! $EUID -eq 0 ]];then
@@ -29,19 +29,19 @@ if [[ ! $EUID -eq 0 ]];then
     exec sudo bash "$0" "$@"
     exit $?
   else
-    echo -e "  ${CROSS} sudo is needed to run pihole commands.  Please run this script as root or install sudo."
+    echo -e "  ${CROSS} sudo is needed to run xfilter commands.  Please run this script as root or install sudo."
     exit 1
   fi
 fi
 
 webpageFunc() {
-  source "${PI_HOLE_SCRIPT_DIR}/webpage.sh"
+  source "${X_FILTER_SCRIPT_DIR}/webpage.sh"
   main "$@"
   exit 0
 }
 
 listFunc() {
-  "${PI_HOLE_SCRIPT_DIR}"/list.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/list.sh "$@"
   exit 0
 }
 
@@ -58,52 +58,52 @@ debugFunc() {
     web="true"
   fi
 
-  AUTOMATED=${automated:-} WEBCALL=${web:-} "${PI_HOLE_SCRIPT_DIR}"/piholeDebug.sh
+  AUTOMATED=${automated:-} WEBCALL=${web:-} "${X_FILTER_SCRIPT_DIR}"/xfilterDebug.sh
   exit 0
 }
 
 flushFunc() {
-  "${PI_HOLE_SCRIPT_DIR}"/piholeLogFlush.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/xfilterLogFlush.sh "$@"
   exit 0
 }
 
-updatePiholeFunc() {
+updateXfilterFunc() {
   shift
-  "${PI_HOLE_SCRIPT_DIR}"/update.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/update.sh "$@"
   exit 0
 }
 
-reconfigurePiholeFunc() {
-  /etc/.pihole/automated\ install/basic-install.sh --reconfigure
+reconfigureXfilterFunc() {
+  /etc/.xfilter/automated\ install/basic-install.sh --reconfigure
   exit 0;
 }
 
 updateGravityFunc() {
-  "${PI_HOLE_SCRIPT_DIR}"/gravity.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/gravity.sh "$@"
   exit $?
 }
 
 queryFunc() {
   shift
-  "${PI_HOLE_SCRIPT_DIR}"/query.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/query.sh "$@"
   exit 0
 }
 
 chronometerFunc() {
   shift
-  "${PI_HOLE_SCRIPT_DIR}"/chronometer.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/chronometer.sh "$@"
   exit 0
 }
 
 
 uninstallFunc() {
-  "${PI_HOLE_SCRIPT_DIR}"/uninstall.sh
+  "${X_FILTER_SCRIPT_DIR}"/uninstall.sh
   exit 0
 }
 
 versionFunc() {
   shift
-  "${PI_HOLE_SCRIPT_DIR}"/version.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/version.sh "$@"
   exit 0
 }
 
@@ -117,7 +117,7 @@ restartDNS() {
     svc="killall -s SIGHUP ${resolver}"
   else
     # Get PID of resolver to determine if it needs to start or restart
-    if pidof pihole-FTL &> /dev/null; then
+    if pidof xfilter-FTL &> /dev/null; then
       svcOption="restart"
     else
       svcOption="start"
@@ -142,19 +142,19 @@ restartDNS() {
   fi
 }
 
-piholeEnable() {
+xfilterEnable() {
   if [[ "${2}" == "-h" ]] || [[ "${2}" == "--help" ]]; then
-    echo "Usage: pihole disable [time]
-Example: 'pihole disable', or 'pihole disable 5m'
-Disable Pi-hole subsystems
+    echo "Usage: xfilter disable [time]
+Example: 'xfilter disable', or 'xfilter disable 5m'
+Disable X-filter subsystems
 
 Time:
-  #s                  Disable Pi-hole functionality for # second(s)
-  #m                  Disable Pi-hole functionality for # minute(s)"
+  #s                  Disable X-filter functionality for # second(s)
+  #m                  Disable X-filter functionality for # minute(s)"
     exit 0
 
   elif [[ "${1}" == "0" ]]; then
-    # Disable Pi-hole
+    # Disable X-filter
     if [[ -e "${gravitylist}" ]]; then
       mv "${gravitylist}" "${gravitylist}.bck"
       echo "" > "${gravitylist}"
@@ -171,7 +171,7 @@ Time:
           local str="Disabling blocking for ${tt} seconds"
           echo -e "  ${INFO} ${str}..."
           local str="Blocking will be re-enabled in ${tt} seconds"
-          nohup bash -c "sleep ${tt}; pihole enable" </dev/null &>/dev/null &
+          nohup bash -c "sleep ${tt}; xfilter enable" </dev/null &>/dev/null &
         else
           local error=true
         fi
@@ -182,7 +182,7 @@ Time:
           echo -e "  ${INFO} ${str}..."
           local str="Blocking will be re-enabled in ${tt} minutes"
           tt=$((${tt}*60))
-          nohup bash -c "sleep ${tt}; pihole enable" </dev/null &>/dev/null &
+          nohup bash -c "sleep ${tt}; xfilter enable" </dev/null &>/dev/null &
         else
           local error=true
         fi
@@ -194,18 +194,18 @@ Time:
 
       if [[ ${error} == true ]];then
         echo -e "  ${COL_LIGHT_RED}Unknown format for delayed reactivation of the blocking!${COL_NC}"
-        echo -e "  Try 'pihole disable --help' for more information."
+        echo -e "  Try 'xfilter disable --help' for more information."
         exit 1
       fi
 
-      local str="Pi-hole Disabled"
+      local str="X-filter Disabled"
       sed -i "/BLOCKING_ENABLED=/d" "${setupVars}"
       echo "BLOCKING_ENABLED=false" >> "${setupVars}"
     fi
   else
-    # Enable Pi-hole
+    # Enable X-filter
     echo -e "  ${INFO} Enabling blocking"
-    local str="Pi-hole Enabled"
+    local str="X-filter Enabled"
 
     if [[ -e "${gravitylist}.bck" ]]; then
       mv "${gravitylist}.bck" "${gravitylist}"
@@ -222,37 +222,37 @@ Time:
   echo -e "${OVER}  ${TICK} ${str}"
 }
 
-piholeLogging() {
+xfilterLogging() {
   shift
   if [[ "${1}" == "-h" ]] || [[ "${1}" == "--help" ]]; then
-    echo "Usage: pihole logging [options]
-Example: 'pihole logging on'
-Specify whether the Pi-hole log should be used
+    echo "Usage: xfilter logging [options]
+Example: 'xfilter logging on'
+Specify whether the X-filter log should be used
 
 Options:
-  on                  Enable the Pi-hole log at /var/log/pihole.log
-  off                 Disable and flush the Pi-hole log at /var/log/pihole.log
-  off noflush         Disable the Pi-hole log at /var/log/pihole.log"
+  on                  Enable the X-filter log at /var/log/xfilter.log
+  off                 Disable and flush the X-filter log at /var/log/xfilter.log
+  off noflush         Disable the X-filter log at /var/log/xfilter.log"
     exit 0
   elif [[ "${1}" == "off" ]]; then
     # Disable logging
-    sed -i 's/^log-queries/#log-queries/' /etc/dnsmasq.d/01-pihole.conf
-    sed -i 's/^QUERY_LOGGING=true/QUERY_LOGGING=false/' /etc/pihole/setupVars.conf
+    sed -i 's/^log-queries/#log-queries/' /etc/dnsmasq.d/01-xfilter.conf
+    sed -i 's/^QUERY_LOGGING=true/QUERY_LOGGING=false/' /etc/xfilter/setupVars.conf
     if [[ "${2}" != "noflush" ]]; then
       # Flush logs
-      pihole -f
+      xfilter -f
     fi
     echo -e "  ${INFO} Disabling logging..."
     local str="Logging has been disabled!"
   elif [[ "${1}" == "on" ]]; then
     # Enable logging
-    sed -i 's/^#log-queries/log-queries/' /etc/dnsmasq.d/01-pihole.conf
-    sed -i 's/^QUERY_LOGGING=false/QUERY_LOGGING=true/' /etc/pihole/setupVars.conf
+    sed -i 's/^#log-queries/log-queries/' /etc/dnsmasq.d/01-xfilter.conf
+    sed -i 's/^QUERY_LOGGING=false/QUERY_LOGGING=true/' /etc/xfilter/setupVars.conf
     echo -e "  ${INFO} Enabling logging..."
     local str="Logging has been enabled!"
   else
     echo -e "  ${COL_LIGHT_RED}Invalid option${COL_NC}
-  Try 'pihole logging --help' for more information."
+  Try 'xfilter logging --help' for more information."
     exit 1
   fi
   restartDNS
@@ -273,33 +273,33 @@ statusFunc() {
     return 0
   fi
 
-  # Determine if Pi-hole's blocking is enabled
-  if grep -q "BLOCKING_ENABLED=false" /etc/pihole/setupVars.conf; then
+  # Determine if X-filter's blocking is enabled
+  if grep -q "BLOCKING_ENABLED=false" /etc/xfilter/setupVars.conf; then
     # A config is commented out
     case "${1}" in
       "web") echo 0;;
-      *) echo -e "  ${CROSS} Pi-hole blocking is Disabled";;
+      *) echo -e "  ${CROSS} X-filter blocking is Disabled";;
     esac
-  elif grep -q "BLOCKING_ENABLED=true" /etc/pihole/setupVars.conf;  then
+  elif grep -q "BLOCKING_ENABLED=true" /etc/xfilter/setupVars.conf;  then
     # Configs are set
     case "${1}" in
       "web") echo 1;;
-      *) echo -e "  ${TICK} Pi-hole blocking is Enabled";;
+      *) echo -e "  ${TICK} X-filter blocking is Enabled";;
     esac
   else
     # No configs were found
     case "${1}" in
       "web") echo 99;;
-      *) echo -e "  ${INFO} Pi-hole blocking will be enabled";;
+      *) echo -e "  ${INFO} X-filter blocking will be enabled";;
     esac
     # Enable blocking
-    pihole enable
+    xfilter enable
   fi
 }
 
 tailFunc() {
-  # Warn user if Pi-hole's logging is disabled
-  local logging_enabled=$(grep -c "^log-queries" /etc/dnsmasq.d/01-pihole.conf)
+  # Warn user if X-filter's logging is disabled
+  local logging_enabled=$(grep -c "^log-queries" /etc/dnsmasq.d/01-xfilter.conf)
   if [[ "${logging_enabled}" == "0" ]]; then
     # No "log-queries" lines are found.
     # Commented out lines (such as "#log-queries") are ignored
@@ -308,13 +308,13 @@ tailFunc() {
   echo -e "  ${INFO} Press Ctrl-C to exit"
 
   # Retrieve IPv4/6 addresses
-  source /etc/pihole/setupVars.conf
+  source /etc/xfilter/setupVars.conf
 
   # Strip date from each line
   # Colour blocklist/blacklist/wildcard entries as red
   # Colour A/AAAA/DHCP strings as white
   # Colour everything else as gray
-  tail -f /var/log/pihole.log | sed -E \
+  tail -f /var/log/xfilter.log | sed -E \
     -e "s,($(date +'%b %d ')| dnsmasq[.*[0-9]]),,g" \
     -e "s,(.*(gravity.list|black.list|regex.list| config ).* is (0.0.0.0|::|NXDOMAIN|${IPV4_ADDRESS%/*}|${IPV6_ADDRESS:-NULL}).*),${COL_RED}&${COL_NC}," \
     -e "s,.*(query\\[A|DHCP).*,${COL_NC}&${COL_NC}," \
@@ -322,16 +322,16 @@ tailFunc() {
   exit 0
 }
 
-piholeCheckoutFunc() {
+xfilterCheckoutFunc() {
   if [[ "$2" == "-h" ]] || [[ "$2" == "--help" ]]; then
-    echo "Usage: pihole checkout [repo] [branch]
-Example: 'pihole checkout master' or 'pihole checkout core dev'
-Switch Pi-hole subsystems to a different Github branch
+    echo "Usage: xfilter checkout [repo] [branch]
+Example: 'xfilter checkout master' or 'xfilter checkout core dev'
+Switch X-filter subsystems to a different Github branch
 
 Repositories:
-  core [branch]       Change the branch of Pi-hole's core subsystem
+  core [branch]       Change the branch of X-filter's core subsystem
   web [branch]        Change the branch of Web Interface subsystem
-  ftl [branch]        Change the branch of Pi-hole's FTL subsystem
+  ftl [branch]        Change the branch of X-filter's FTL subsystem
 
 Branches:
   master              Update subsystems to the latest stable release
@@ -340,7 +340,7 @@ Branches:
     exit 0
   fi
 
-  source "${PI_HOLE_SCRIPT_DIR}"/piholeCheckout.sh
+  source "${X_FILTER_SCRIPT_DIR}"/xfilterCheckout.sh
   shift
   checkout "$@"
 }
@@ -351,13 +351,13 @@ tricorderFunc() {
     exit 1
   fi
 
-  if ! (echo > /dev/tcp/tricorder.pi-hole.net/9998) >/dev/null 2>&1; then
-    echo -e "  ${CROSS} Unable to connect to Pi-hole's Tricorder server"
+  if ! (echo > /dev/tcp/tricorder.x-filter.net/9998) >/dev/null 2>&1; then
+    echo -e "  ${CROSS} Unable to connect to X-filter's Tricorder server"
     exit 1
   fi
 
   if command -v openssl &> /dev/null; then
-    openssl s_client -quiet -connect tricorder.pi-hole.net:9998 2> /dev/null < /dev/stdin
+    openssl s_client -quiet -connect tricorder.x-filter.net:9998 2> /dev/null < /dev/stdin
     exit "$?"
   else
     echo -e "  ${INFO} ${COL_YELLOW}Security Notice${COL_NC}: ${COL_WHITE}openssl${COL_NC} is not installed
@@ -371,19 +371,19 @@ tricorderFunc() {
        : $((secs--))
     done
     echo " "
-    nc tricorder.pi-hole.net 9999 < /dev/stdin
+    nc tricorder.x-filter.net 9999 < /dev/stdin
     exit "$?"
   fi
 }
 
 updateCheckFunc() {
-  "${PI_HOLE_SCRIPT_DIR}"/updatecheck.sh "$@"
+  "${X_FILTER_SCRIPT_DIR}"/updatecheck.sh "$@"
   exit 0
 }
 
 helpFunc() {
-  echo "Usage: pihole [options]
-Example: 'pihole -w -h'
+  echo "Usage: xfilter [options]
+Example: 'xfilter -w -h'
 Add '-h' after specific commands for more information on usage
 
 Whitelist/Blacklist Options:
@@ -396,9 +396,9 @@ Whitelist/Blacklist Options:
 Debugging Options:
   -d, debug           Start a debugging session
                         Add '-a' to enable automated debugging
-  -f, flush           Flush the Pi-hole log
-  -r, reconfigure     Reconfigure or Repair Pi-hole subsystems
-  -t, tail            View the live output of the Pi-hole log
+  -f, flush           Flush the X-filter log
+  -r, reconfigure     Reconfigure or Repair X-filter subsystems
+  -t, tail            View the live output of the X-filter log
 
 Options:
   -a, admin           Web interface options
@@ -407,21 +407,21 @@ Options:
                         Add '-h' for more info on chronometer usage
   -g, updateGravity   Update the list of ad-serving domains
   -h, --help, help    Show this help dialog
-  -l, logging         Specify whether the Pi-hole log should be used
+  -l, logging         Specify whether the X-filter log should be used
                         Add '-h' for more info on logging usage
   -q, query           Query the adlists for a specified domain
                         Add '-h' for more info on query usage
-  -up, updatePihole   Update Pi-hole subsystems
+  -up, updateXfilter   Update X-filter subsystems
                         Add '--check-only' to exit script before update is performed.
-  -v, version         Show installed versions of Pi-hole, Web Interface & FTL
+  -v, version         Show installed versions of X-filter, Web Interface & FTL
                         Add '-h' for more info on version usage
-  uninstall           Uninstall Pi-hole from your system
-  status              Display the running status of Pi-hole subsystems
-  enable              Enable Pi-hole subsystems
-  disable             Disable Pi-hole subsystems
+  uninstall           Uninstall X-filter from your system
+  status              Display the running status of X-filter subsystems
+  enable              Enable X-filter subsystems
+  disable             Disable X-filter subsystems
                         Add '-h' for more info on disable usage
-  restartdns          Restart Pi-hole subsystems
-  checkout            Switch Pi-hole subsystems to a different Github branch
+  restartdns          Restart X-filter subsystems
+  checkout            Switch X-filter subsystems to a different Github branch
                         Add '-h' for more info on checkout usage";
   exit 0
 }
@@ -438,22 +438,22 @@ case "${1}" in
   "--regex" | "regex"            ) listFunc "$@";;
   "-d" | "debug"                ) debugFunc "$@";;
   "-f" | "flush"                ) flushFunc "$@";;
-  "-up" | "updatePihole"        ) updatePiholeFunc "$@";;
-  "-r"  | "reconfigure"         ) reconfigurePiholeFunc;;
+  "-up" | "updateXfilter"        ) updateXfilterFunc "$@";;
+  "-r"  | "reconfigure"         ) reconfigureXfilterFunc;;
   "-g" | "updateGravity"        ) updateGravityFunc "$@";;
   "-c" | "chronometer"          ) chronometerFunc "$@";;
   "-h" | "help"                 ) helpFunc;;
   "-v" | "version"              ) versionFunc "$@";;
   "-q" | "query"                ) queryFunc "$@";;
-  "-l" | "logging"              ) piholeLogging "$@";;
+  "-l" | "logging"              ) xfilterLogging "$@";;
   "uninstall"                   ) uninstallFunc;;
-  "enable"                      ) piholeEnable 1;;
-  "disable"                     ) piholeEnable 0 "$2";;
+  "enable"                      ) xfilterEnable 1;;
+  "disable"                     ) xfilterEnable 0 "$2";;
   "status"                      ) statusFunc "$2";;
   "restartdns"                  ) restartDNS "$2";;
   "-a" | "admin"                ) webpageFunc "$@";;
   "-t" | "tail"                 ) tailFunc;;
-  "checkout"                    ) piholeCheckoutFunc "$@";;
+  "checkout"                    ) xfilterCheckoutFunc "$@";;
   "tricorder"                   ) tricorderFunc;;
   "updatechecker"               ) updateCheckFunc "$@";;
   *                             ) helpFunc;;
